version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/test/
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
